# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  - name: "resources"
    label: "Resources"
    folder: "_resources"
    create: true
    filter: {
      field: "published"
      value: "true"
    }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Organization", name: "organization", widget: "string" }
      - { label: "Date Published", name: "date_published", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Link", name: "url", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Regions/Countries", name: "geographical_units", widget: "list" }
      - { label: "Languages", name: "languages", widget: "list" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Date Added", name: "created", widget: "datetime" }
      - { label: "Last Updated", name: "last_modified", widget: "datetime" }
      - { label: "Published", name: "published", widget: "boolean" }
